server:
  # gateway使用的端口
  port: 8040
spring:
  application:
    # 指定gateway注册到nacos上面的名称
    name: gateway
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true
      routes:
#        - id: after_route
#          uri: lb://user-center
#          predicates:
#            - TimeBetween=上午0:00,下午11:59
#          filters:
#            - AddRequestHeader=X-Request-Foo, Bar
#            - PreLog=a, b
        - id: user_route
            uri: lb://user-center
            predicates:
              - Path=/users/**
        - id: content_route
            uri: lb://content-center
            predicates:
              - Path=/shares/**,/admin/**
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
